# Generated by Django 5.0.6 on 2024-05-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
